SEARCH_MOVIE = 'http://api.themoviedb.org/2.1/Movie.search/en/xml/'
API_KEY = '7be21ddb70e82fa45ac8042abbe3ab0d'
ENTER_SOMETHING_VALID = 'Invalid Input'
COULD_NOT_FIND_MOVIE = 'Could not find Movie, you might want to check spellings'
SUMMARY = 'Brief summary of your search, enter the index on your left to know more'
